%YAML 1.1
---
title: Clean Filter for SVG
name: clean-filter-for-svg
summary: A clean filter for stripping unnecessary metadata in SVGs
description: |
  A clean filter for SVG for Git and other applications. Currently it strips out personal information and metadata not suited for version controlling.

  https://github.com/Lin-Buo-Ren/Clean-Filter-for-SVG

license: GPL-3.0

adopt-info: main
base: core
confinement: strict
grade: stable

parts:
  main:
    after:
    - selective-checkout
    source: .
    override-pull: |
      set -o nounset

      snapcraftctl pull
      # Drop local gitconfig filter setup
      # NOTE: This won't affect project dir git config as it modifies the config in SNAPCRAFT_PART_SRC
      git config \
        --unset \
        include.path \
        || test "${?}" = 5
      "$SNAPCRAFT_STAGE"/scriptlets/selective-checkout

    plugin: dump
    organize:
      # Workaround Snapcraft's app._app_name_.command property restricion
      # https://forum.snapcraft.io/t/pattern-mismatch-in-the-app-app-name-command-property/12494
      Clean Filter for SVG.bash: clean-filter-for-svg
    stage:
    - clean-filter-for-svg
    - Libraries/*
    - README.markdown

  xmlstarlet:
    plugin: nil
    stage-snaps:
    - xmlstarlet

  # Check out the tagged release revision if it isn't promoted to the stable channel
  # https://forum.snapcraft.io/t/selective-checkout-check-out-the-tagged-release-revision-if-it-isnt-promoted-to-the-stable-channel/10617
  selective-checkout:
    plugin: nil
    build-packages:
    - git
    stage-snaps:
    - selective-checkout
    prime:
    - -*

apps:
  clean-filter-for-svg:
    adapter: full
    command: clean-filter-for-svg

  # DISABLED: Not working for now
  # https://forum.snapcraft.io/t/pattern-mismatch-in-the-app-app-name-command-property/12494
  #readme:
    #adapter: full
    #command: /usr/bin/less README.markdown

plugs:
  # For regular file access of the converter mode
  home:
  removable-media:
